name: Docker Workflow

on:
  push:
    branches:
      - main

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: humble15/resume-app

permissions:
  id-token: write
  contents: write
  packages: write

jobs: 
  docker_build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Login to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and Tag Docker Image
      run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest .

    - name: Push Image to DockerHub
      run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: GHCR Login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}  
        password: ${{ secrets.GITHUB_TOKEN }}  

    - name: Build and Tag for GHCR
      run: docker build -t ghcr.io/${{ github.actor }}/resume-app:latest .

    - name: Push Image to GHCR
      run: docker push ghcr.io/${{ github.actor }}/resume-app:latest
