name: Docker Workflow

on:
  push:
    branches:
      - main

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: resume-app

jobs: 
  docker_build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Debug Docker Username
      run: |
        echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"

    - name: Docker Login to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and Tag Docker Image
      run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/resume-app:latest .

    - name: Publish code to DockerHub
      run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/resume-app:latest
